### ISSUE TITLE
EPIC: Technology Eval and Selection

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#11]
- [x] Evaluate persistent storage technologies #15
- [x] Evaluate streaming/event technologies #16
- [x] Select persistent storage technology #15
- [x] Select streaming/event technology #16

**Comment by dneufeldcu** [comment]
Team has selected Kafka
