### ISSUE TITLE
EPIC: Security Set-up and Review

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#12]
- [x] OWASP dependency check in gradle builds
- [ ] RetireJS, NSP checks
- [x] Application props for spring env set false
