### ISSUE TITLE
CCI deployed to CU Infrastructure

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#13]

**Comment by mcquinne** [comment]
This is a follow-on to #24 but with the rest of the ingest engines deployed, with the exception of those we don't intend to support going forward, e.g. dscovr.

**Comment by ChrisEsterlein** [comment]
There are a few ongoing issues that need to be resolved for this to be complete:
- [ x ] VMs need shared volume (gluster)
- [ x ] oracle container uses shared volume
- [ ] common ingest system uses shared volume (update configs and test)
- [ ] RabbitMQ container needs to use shared volume
- [ ] Fix oracle container restart issues (fails if mounted volume has data)
- [ ] port usage scheme (we are all over the place)

**Comment by ChrisEsterlein** [comment]
common_ingest stack ports (for now) -  
- chomp 42100
- ingest-manager 42101
- rabbit 42102

**Comment by ChrisEsterlein** [comment]
The oracle issue - 
We are using default docker storage settings, which uses a loopback storage device. It is a known issue and breaks the oracle container when run in a swarm. See https://github.com/MaksymBilenko/docker-oracle-12c/issues/59

We already use the correct storage drive, devicemapper, but we are still using the default loopback device. 

If you go to CU VM1, run ```docker info```, you will see that we are using loopback 
> Data file: /dev/loop0
 Metadata file: /dev/loop1

We need to add create a storage area for docker and then update /etc/sysconfig/docker-storage with ```DOCKER_STORAGE_OPTIONS=-s devicemapper --storage-opt dm.datadev=/<path>/<to>/<docker-data> --storage-opt dm.metadatadev=/<path>/<to>/<docker-metadata>```

Then we will need to restart the docker daemon. 

I am going to wait until after Zeb's accessibility consultation and then I am going to make this change.

**Comment by ChrisEsterlein** [comment]
dockerd service starts with device mapper. 

in /usr/lib/systemd/system/docker.service- 
```ExecStart=/usr/bin/dockerd -s devicemapper -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock```

**Comment by ChrisEsterlein** [comment]
We have deployed CCI to CU, added necessary infrastructure (gluster), and tested a simple move file stream and also the new generic dscovr stream. 

Also, regarding my last message - After the VMs got wiped, Evan configured docker to use overlay2 instead of devicemapper as per the recommendation from docker. Everything seems to be operating normally. 

This story is SO closed.
