### ISSUE TITLE
Docker infra set-up on cedardevs AWS

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#14]
- [x] finish registration process (required phone verification)
- [x] set up aws user
- [x] set up ansible to talk to aws
- [x] ~spin up ec2 instances with ansible~ use cloudformation 
- [x] download docker and set up swarm

**Comment by ChrisEsterlein** [comment]
- [ x ] finish registration process (required phone verification)
- [ ] set up aws user
- [ ] set up ansible to talk to aws
- [ ] spin up ec2 instances with ansible
- [ ] download docker and set up swarm
- [ ] deploy a stack!

**Comment by mcquinne** [comment]
AWS work captured here: https://github.com/cedardevs/aws-admin
