### ISSUE TITLE
EPIC: Metadata Validation

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/psi#140]

**Comment by mcquinne** [comment]
### Background
There are a number of validation rules that have been implemented by the OneStop metadata developers. Currently, those rules are executed manually which is onerous and inefficient. We would like to fold those rules into our streaming metadata processing system as serverless functions (requires #100).

### Acceptance Criteria
The validation steps are implemented as serverless functions and run automatically on every granule and collection coming through the system.

### Tasks
- [ ] Assess validation code and identify function boundaries
- [ ] Implement validation steps as serverless functions
- [ ] Fold validation into processing workflow for all collections and granules
- [ ] Persist validation results
- [ ] Utilize validation results to filter outputs to OneStop

**Comment by StrayCat1** [comment]
Made good progress today on understanding the business rules we want to support and also as a team we pretty much decided where this code should live (after parsing, before the parsed-granules topic). Implementing it should be pretty straight forward. 

What kind of validation results do we want to keep? I have been assuming the XML is either valid or not, but I guess we could have validation logic that makes suggestions on what could be done better.

Records that don't pass critical validation steps will not go to parsed-granules and thus will not go to OneStop, instead they will go to the error topic. The Kstream app that validates, will branch based on the result. 

I could totally implement these validation steps as an OpenWhisk action pretty quickly.
