### ISSUE TITLE
Dscovr parse and store granule metadata

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#19]
Filename metadata is parsed and stored as JSON

- [ ] Refactor metadata-record into lightengine approach
- [ ] Write test and implement dscovr granule flowing through metadata recorder and retreive filepath info  
- [ ] Explore JSON processing options in a streaming context

**Comment by cEsterlein** [comment]
See #42
