### ISSUE TITLE
kafka set-up

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#37]
- [x] kafka container available
- [x] 3 node kafka cluster (2 scalable services, kafka + zookeeper tested in a vagrant swarm) 
- [ ] schema registry
- [ ] topic UI from landoop

**Comment by ChrisEsterlein** [comment]
Started with the confluent tutorial found [here](https://docs.confluent.io/current/installation/docker/docs/tutorials/clustered-deployment.html)
Which uses the docker compose found [here](https://github.com/confluentinc/cp-docker-images/blob/4.0.x/examples/kafka-cluster/docker-compose.yml)

And that all worked pretty much right out of the box but with one thing I did not like - you had to publish/consume kafka from inside a container. So I spent some time figuring out a config that would allow you to administer kafka from your host machine (and in so doing, learned some good stuff about how kafka and zookeeper interact. Here is the compose I came up with-

```

---
version: '3'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:22181"
      - "22888:23888"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "32181:32181"
      - "32888:33888"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "42181:42181"
      - "42888:43888"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888


  kafka-1:
    image: confluentinc/cp-kafka:latest
    # network_mode: host
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$(ipconfig getifaddr en0):19092


  kafka-2:
    image: confluentinc/cp-kafka:latest
    # network_mode: host
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$(ipconfig getifaddr en0):29092


  kafka-3:
    image: confluentinc/cp-kafka:latest
    # network_mode: host
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$(ipconfig getifaddr en0):39092
```

Compose files aren't dynamic, so replace $(ipconfig getifaddr en0) with your actual ip address. 

Next up- deploy this as a stack

**Comment by ChrisEsterlein** [comment]
I didn't like having to define 3 zookeeper services and 3 kafka services. I want to be able to define 1 zookeeper service and 1 kafka service and scale them as needed. Confluent did it this way because of the complex listener configurations, but newer versions of kafka offer more flexible listener configurations- which we need in order to create a services that can scale. 

More on that here: https://hub.docker.com/r/wurstmeister/kafka/

In short, here is a docker-compose.yml that defines 2 services, one zookeeper and one kafka. If we choose to scale them n number of times, we can do that with ```docker service scale <name>=n```

```
version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9094
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
I've tested this on a local vagrant cluster. I am going to add it to the cu-server-admin project as the first pass on a psi stack.

**Comment by ChrisEsterlein** [comment]
working on adding a schema registry and topic ui to this

**Comment by ChrisEsterlein** [comment]
more on why I did not use confluent's kafka image
https://github.com/confluentinc/cp-docker-images/issues/213

**Comment by RevRedcreek** [comment]
Might be blocked on adding the schema- my woes are referenced in this issue
https://github.com/confluentinc/schema-registry/issues/648

**Comment by cEsterlein** [comment]
Yeah so I dont know what else to do here. I have a scalable kafka and zookeeper compose that  allow you to interact with it from the outside, but doesnt work with the schema registry and therefore it also doesnt work with the landoop ui. I have a compose with non-scalable kafka and zookeeper services that work with the schema registry, rest proxy, and ui, but can't be interacted with outside of a docker container.  

The simple single node kafka + zookeeper that can be interacted with from the host machine seems to be our best and only option for local development.
