### ISSUE TITLE
EPIC: PSI DSCOVR datastream

### ISSUE THREAD

**Issue by cEsterlein** [cedardevs/psi#42]
Filename metadata is parsed and stored as JSON

- [x] Refactor metadata-record into lightengine approach
- [x] Write test and implement dscovr granule flowing through metadata recorder and retreive filepath info  
- [x] Explore JSON processing options in a streaming context
- [x] Insert granule into onestop
- [x] Insert collection into onestop
- [x] Records are visible in Onestop UI
