### ISSUE TITLE
First pass parser app

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/psi#43]
- [ ] Create a new subproject called parser
- [ ] Create a KafaStreams instance which reads from the raw granule changelog
- [ ] Implement a dscovr parser function
- [ ] For each message determine which parser function to call (only dscovr for now)
- [ ] Publish parsed metadata to a new topic
