### ISSUE TITLE
Bug: kafka-ui can't reach kafka-rest

### ISSUE THREAD

**Issue by cEsterlein** [cedardevs/psi#64]
Kafka-ui needs kafka-rest to get topic info. It appears kafka-rest is listening, but I can't reach it on the port exposed on the host either. I get connection refused.

**Comment by cEsterlein** [comment]
Shifting focus away from UI toward kafka-rest itself. It seems kafka-rest is the problem. Until we can get that working, there is no point in troubleshooting the UI. 

Here is what I know so far- 
1) the kafka-ui can't connect to kafka-rest
2) we can't manually connect to kafka-rest
3)  All of the config params we are using in the stack work in the compose- I can curl kafka-rest @ localhost when everything is running locally
4) There is a service listening on the port we published to kafka-rest 
5) Using a different port did not work

**Comment by cEsterlein** [comment]
I am going to try  [kafka-manager](https://github.com/yahoo/kafka-manager)

- [ ] create image for kafka-manager
- [ ] run it locally
- [ ] deploy to CU
