### ISSUE TITLE
EPIC: Discovery support for Stennis Video datastream

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#86]
Determined that there's alot of domain specific logic.  So instead of starting with ingest, look to Stennis to allow publishing to OneStop on sciapps.

- [x] Get reference ISOlite records from MS/MD (i.e. ~100 records) (Parent of #113)
- [x] Use a simple splitter app to route messages to topic (Parent of #129)
- [x] Simulate metadata publishing from MS/MD  based on metadata records provided to us  (See https://www.nodc.noaa.gov/search/granule/ and search for "EX1603". Download any or all metadata records found.) (Parent of #114)
- [x] Add granule endpoint to publisher to support XML (Parent of #133)
- [x] Harvest ~1000~ 500 OER video records and post to granule endpoint (Parent of #134)
- [x] Video streaming support for mp4 on a WAF (OneStop story) (Parent of #115)
- [ ] Provide feedback to OER metadata managers (parent of #139)
