### ISSUE TITLE
EPIC: DSCOVR Hardening

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#87]
Revisit issues that came from first pass epic dscovr datastream support in PSI
- [ ] Create a metadata-publisher engine (Parent of #91)
- [x] Bug: CI Event Order (Parent of #67)
- [ ] Embargo feature (Parent of #71)
- [ ] error topic connector (Parent of #119, Parent of #120)
