### ISSUE TITLE
EPIC: CSB CCOG

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#97]
Background: Crowd Sourced Bathymetry is a datastream running at NCEI-CO. Files from ships containing location, depth and time are posted to ingest-external as xyzt and converted to GeoJSON.  GeoJSON files are also available to be downloaded via a mapviewer. See https://maps.ngdc.noaa.gov/viewers/csb/index.html

CCOG:
- [x] Review file permissions and understand if it will re-occur in 2019
- [ ] Adjust landing zone ticket to follow (Dave F. nfs mount)
- [ ] Ingest hardening - meaning how will the system scale with increasing loads
  - [ ] Documentation on how to add data providers
  - [ ] Review line generalization code adjust if needed
  - [ ] Monitoring tools
- [ ] Extract hardening - meaning how will the system scale with increasing loads
  - [ ] Review catalog-index (DB performance)? 
  - [ ] Review line generalization code adjust if needed
  - [ ] Monitoring tools
- [ ] Add additional format converter to ingest/extract pipeline
   - [ ] kml - Aaron to manage python code
   - [ ] shp? - Aaron to manage python code
- [ ] Review disk space needs on partner environment

- [ ] Improve on boarding process for new providers vs manual process currently (confirm whether we need to do this with Dave F.)
- [ ] Some NEXT UI tweaks - work with Aaron where possible to ramp him up on code and pull requests
  - [ ] Replace ngdc with ncei in tarball extracts.
CSB related work will be tracked on the PSI board even though some tasks may be more specific to CCOG needs.

**Comment by dneufeldcu** [comment]
Moved to maintenance board.
