### ISSUE TITLE
EPIC: CSB MSN

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#98]
Background: Crowd Sourced Bathymetry is a datastream running at NCEI-CO. Files from ships containing location, depth and time are posted to ingest-external as xyzt and converted to GeoJSON.  GeoJSON files are also available to be downloaded via a mapviewer. See https://maps.ngdc.noaa.gov/viewers/csb/index.html

MSN tasks (partner production env not supported aka target env CIRES or Cloud):
- [ ] Deploy existing PSI system to cloud - AWS #32
- [ ] Simulate CSB (Rosepoint) ingest-external in cloud or CIRES (discuss)
- [ ] Migrate existing file based ingest/extract to workflow to OneStop  
- [ ] Spike ElasticSearch point store for CSB

CSB related work will be tracked on the PSI board even though some tasks may be more specific to CCOG needs.
